"""empty message

Revision ID: eb64c940a324
Revises: 
Create Date: 2020-12-29 11:30:40.483961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb64c940a324'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_department',
    sa.Column('id', sa.String(length=20), autoincrement=False, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值，0为已删除，1为正常，2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者ID'),
    sa.Column('idx', sa.SmallInteger(), nullable=True, comment='显示排序'),
    sa.Column('department_name', sa.String(length=30), nullable=False, comment='部门名称'),
    sa.Column('remarks', sa.String(length=200), nullable=True, comment='备注说明'),
    sa.Column('parent_id', sa.String(length=20), nullable=True, comment='部门父级ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='后台部门表'
    )
    op.create_index(op.f('ix_sys_department_change_by_id'), 'sys_department', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_sys_department_create_by_id'), 'sys_department', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_sys_department_deleted_by_id'), 'sys_department', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_sys_department_parent_id'), 'sys_department', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_department_state'), 'sys_department', ['state'], unique=False)
    op.create_table('sys_user',
    sa.Column('id', sa.String(length=20), autoincrement=False, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值，0为已删除，1为正常，2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者ID'),
    sa.Column('login_name', sa.String(length=30), nullable=False, comment='登录名'),
    sa.Column('password', sa.String(length=50), nullable=False, comment='密码'),
    sa.Column('user_name', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('gender', sa.SmallInteger(), nullable=False, comment='性别， 0为未知，1为男，2为女'),
    sa.Column('phone', sa.String(length=30), nullable=False, comment='手机号码'),
    sa.Column('wechat_no', sa.String(length=30), nullable=True, comment='微信号'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='生日'),
    sa.Column('department_id', sa.String(length=20), nullable=True, comment='部门ID'),
    sa.Column('role_id', sa.String(length=20), nullable=True, comment='角色ID'),
    sa.Column('remarks', sa.String(length=200), nullable=True, comment='备注说明'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_change_by_id'), 'sys_user', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_sys_user_create_by_id'), 'sys_user', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_sys_user_deleted_by_id'), 'sys_user', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_sys_user_department_id'), 'sys_user', ['department_id'], unique=False)
    op.create_index(op.f('ix_sys_user_role_id'), 'sys_user', ['role_id'], unique=False)
    op.create_index(op.f('ix_sys_user_state'), 'sys_user', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_state'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_role_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_department_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_deleted_by_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_create_by_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_change_by_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_department_state'), table_name='sys_department')
    op.drop_index(op.f('ix_sys_department_parent_id'), table_name='sys_department')
    op.drop_index(op.f('ix_sys_department_deleted_by_id'), table_name='sys_department')
    op.drop_index(op.f('ix_sys_department_create_by_id'), table_name='sys_department')
    op.drop_index(op.f('ix_sys_department_change_by_id'), table_name='sys_department')
    op.drop_table('sys_department')
    # ### end Alembic commands ###
